In [1]:
import numpy as np
from utils import *
import matplotlib.pyplot as plt

In [2]:
X_train_orig, Y_train_orig, X_test_orig = load_datasets()
Y_train_orig = Y_train_orig.astype('float64')
Y_train_orig = Y_train_orig.reshape(1,len(Y_train_orig))
print(X_train_orig)
print(Y_train_orig.shape)
print(Y_train_orig)
print(X_test_orig)

[[3 1 3 ... 3 1 3]
 ['male' 'female' 'female' ... 'female' 'male' 'male']
 [22.0 38.0 26.0 ... 29.69911764705882 26.0 32.0]
 [1 1 0 ... 1 0 0]
 [0 0 0 ... 2 0 0]
 [7.25 71.2833 7.925 ... 23.45 30.0 7.75]]
(1, 891)
[[0. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1. 1. 1.
  0. 1. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 1.
  0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0.
  0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
  0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 1. 0. 1. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0.
  0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0.
  0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0.
  1. 1. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 1. 0. 1. 0. 0. 0. 1.
  1. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0.
  0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0.

In [3]:
X_train, X_test = pre_process_data(X_train_orig, X_test_orig)
print(X_train)
print(X_test)
print(X_train.shape)
print(X_test.shape)

[[0.8273772438659676 -1.5661069258891531 0.8273772438659676 ...
  0.8273772438659676 -1.5661069258891531 0.8273772438659676]
 [-0.7376951317802897 1.3555735383351184 1.3555735383351184 ...
  1.3555735383351184 -0.7376951317802897 -0.7376951317802897]
 [-0.5924805998028886 0.638789012042525 -0.2846631968415352 ...
  4.374348392294584e-15 -0.2846631968415352 0.17706290760049492]
 [0.43279336567850346 0.43279336567850346 -0.4745451962498414 ...
  0.43279336567850346 -0.4745451962498414 -0.4745451962498414]
 [-0.473673609298456 -0.473673609298456 -0.473673609298456 ...
  2.0089333664952163 -0.473673609298456 -0.473673609298456]
 [-0.5024451714361915 0.7868452935884467 -0.4888542575852478 ...
  -0.1762632390135436 -0.0443810379414236 -0.49237782784289985]]
[[0.8734819050636105 0.8734819050636105 -0.3158191904301653 ...
  0.8734819050636105 0.8734819050636105 0.8734819050636105]
 [-0.755928946018455 1.322875655532296 -0.755928946018455 ...
  -0.755928946018455 -0.755928946018455 -0.755928946

In [4]:
from sklearn.tree import DecisionTreeClassifier

In [5]:
classifier = DecisionTreeClassifier(criterion = "entropy", random_state = 0)
classifier.fit(X_train.T, Y_train_orig.T)


DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [6]:
y_pred = classifier.predict(X_train.T)

In [7]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_train_orig.T, y_pred)

In [8]:
y_train = np.squeeze(Y_train_orig.T)
print(cm)
print(y_pred.shape)
print(y_train.shape)

[[547   2]
 [ 14 328]]
(891,)
(891,)


In [9]:
accuracy = 100 - np.mean(np.abs(y_train-y_pred))*100
# print(y_train-y_pred)

In [10]:
print("training accuracy for decision trees : ", accuracy)

training accuracy for decision trees :  98.20426487093154


In [11]:
y_test = classifier.predict(X_test.T)
print(y_test)

[0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 0. 1. 0. 0.
 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0.
 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1. 1. 1. 0. 0. 1. 1. 0.
 0. 0. 1. 0. 0. 0. 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.
 1. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 1.
 1. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 0. 0. 0. 1. 0.
 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 0. 0. 0. 0.
 1. 1. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.
 1. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1.
 1. 1. 1. 0. 1. 0. 1. 0. 1. 1. 1. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 1.
 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0.
 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 1. 1. 0. 0. 0.
 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0.

In [12]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 6, criterion = 'entropy', random_state = 0)
classifier.fit(X_train.T, Y_train_orig.T)


/home/arkasarkar/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=6, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [13]:
y_pred = classifier.predict(X_train.T)

In [14]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_train_orig.T, y_pred)

In [15]:
y_train = np.squeeze(Y_train_orig.T)
print(cm)
print(y_pred.shape)
print(y_train.shape)

[[543   6]
 [ 30 312]]
(891,)
(891,)


In [16]:
accuracy = 100 - np.mean(np.abs(y_train-y_pred))*100


In [17]:
print("training accuracy for random forest : ", accuracy)

training accuracy for random forest :  95.95959595959596


In [18]:
y_test = classifier.predict(X_test.T)
print(y_test)

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 0. 0. 1. 1.
 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0.
 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0.
 0. 0. 1. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 1. 0. 0. 0.
 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 1.
 1. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0.
 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0.
 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1.
 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1.
 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0.
 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0.
 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0.