In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

In [2]:
#preprocessing step 
dataset = pd.read_csv('datasets_19_420_Iris.csv').sample(frac = 1)
dataset = dataset.drop(['Id'], axis = 1)
dataset = np.array(dataset)
X = dataset[:, : -1]
Y = dataset[: , -1]
label_enc = preprocessing.LabelEncoder()
label_enc.fit(['Iris-virginica','Iris-versicolor','Iris-setosa'])
Y = label_enc.transform(Y)
Y=Y.reshape(Y.shape[0],1)
print(X)
print(Y)

[[5.8 2.7 5.1 1.9]
 [6.3 2.3 4.4 1.3]
 [6.7 3.1 4.7 1.5]
 [6.8 3.0 5.5 2.1]
 [4.6 3.2 1.4 0.2]
 [4.8 3.0 1.4 0.1]
 [6.5 2.8 4.6 1.5]
 [6.1 3.0 4.9 1.8]
 [6.4 3.2 4.5 1.5]
 [4.4 2.9 1.4 0.2]
 [7.7 2.8 6.7 2.0]
 [6.2 2.9 4.3 1.3]
 [7.7 3.0 6.1 2.3]
 [5.4 3.7 1.5 0.2]
 [5.9 3.0 4.2 1.5]
 [5.8 2.7 3.9 1.2]
 [7.2 3.2 6.0 1.8]
 [5.0 2.3 3.3 1.0]
 [5.1 3.7 1.5 0.4]
 [4.4 3.0 1.3 0.2]
 [5.4 3.9 1.7 0.4]
 [5.5 2.5 4.0 1.3]
 [6.3 2.9 5.6 1.8]
 [6.8 2.8 4.8 1.4]
 [6.0 2.9 4.5 1.5]
 [6.4 2.9 4.3 1.3]
 [7.4 2.8 6.1 1.9]
 [4.8 3.1 1.6 0.2]
 [5.7 2.5 5.0 2.0]
 [5.0 3.2 1.2 0.2]
 [7.2 3.6 6.1 2.5]
 [5.4 3.4 1.7 0.2]
 [4.3 3.0 1.1 0.1]
 [7.9 3.8 6.4 2.0]
 [6.2 3.4 5.4 2.3]
 [4.6 3.1 1.5 0.2]
 [5.3 3.7 1.5 0.2]
 [6.0 3.0 4.8 1.8]
 [5.1 3.8 1.9 0.4]
 [4.9 2.5 4.5 1.7]
 [7.7 2.6 6.9 2.3]
 [6.7 3.3 5.7 2.1]
 [5.9 3.2 4.8 1.8]
 [6.5 3.0 5.8 2.2]
 [5.5 2.4 3.7 1.0]
 [5.1 3.3 1.7 0.5]
 [5.0 3.0 1.6 0.2]
 [6.7 3.0 5.0 1.7]
 [6.9 3.1 5.1 2.3]
 [5.2 3.5 1.5 0.2]
 [6.7 3.1 5.6 2.4]
 [6.0 2.2 5.0 1.5]
 [5.2 2.7 3.

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.25, random_state = 0)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(112, 4)
(38, 4)
(112, 1)
(38, 1)


In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)
print(X_test.shape)
print(X_train.shape)

(38, 4)
(112, 4)


/home/arkasarkar/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/home/arkasarkar/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/home/arkasarkar/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/home/arkasarkar/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [5]:
from sklearn.svm import SVC
model = SVC(kernel = 'rbf', decision_function_shape='ovo', random_state = 0)
model.fit(X_train, Y_train)

/home/arkasarkar/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=0,
  shrinking=True, tol=0.001, verbose=False)

In [6]:
y_pred = model.predict(X_test)

In [7]:
print(y_pred)

[0 1 2 0 2 1 2 2 1 1 2 1 1 0 1 1 0 1 0 2 1 2 1 1 0 2 1 2 0 2 1 0 0 1 1 2 0
 0]


In [8]:
Y_test = np.squeeze(Y_test)
print(Y_test)

[0 1 2 0 2 1 2 2 2 1 2 2 1 0 1 2 0 1 0 2 1 2 1 1 0 2 1 2 0 2 1 0 0 1 1 2 0
 0]


In [9]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)

In [10]:
print(cm)

[[11  0  0]
 [ 0 13  0]
 [ 0  3 11]]


In [11]:
cor = 0

for i in range (len(y_pred)):
    if(y_pred[i]==Y_test[i]):
        cor = cor + 1
print("Test set accuracy is : " , cor*100/ len(y_pred) ,"%" )

Test set accuracy is :  92.10526315789474 %
