In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing


In [2]:
#preprocessing step 
dataset = pd.read_csv('datasets_19_420_Iris.csv').sample(frac = 1)
dataset = dataset.drop(['Id'], axis = 1)
dataset = np.array(dataset)
X = dataset[:, : -1]
Y = dataset[: , -1]
label_enc = preprocessing.LabelEncoder()
label_enc.fit(['Iris-virginica','Iris-versicolor','Iris-setosa'])
Y = label_enc.transform(Y)
Y=Y.reshape(Y.shape[0],1)
print(X)
print(Y)

[[6.4 3.2 4.5 1.5]
 [5.5 2.4 3.7 1.0]
 [6.2 3.4 5.4 2.3]
 [7.2 3.2 6.0 1.8]
 [5.4 3.0 4.5 1.5]
 [6.5 2.8 4.6 1.5]
 [6.0 3.4 4.5 1.6]
 [5.5 2.3 4.0 1.3]
 [4.8 3.0 1.4 0.3]
 [5.6 2.9 3.6 1.3]
 [5.9 3.0 4.2 1.5]
 [5.1 2.5 3.0 1.1]
 [6.3 2.7 4.9 1.8]
 [4.6 3.4 1.4 0.3]
 [4.8 3.4 1.6 0.2]
 [5.1 3.8 1.5 0.3]
 [6.4 3.1 5.5 1.8]
 [5.9 3.0 5.1 1.8]
 [6.5 3.2 5.1 2.0]
 [7.2 3.0 5.8 1.6]
 [6.0 2.9 4.5 1.5]
 [5.7 2.6 3.5 1.0]
 [5.2 2.7 3.9 1.4]
 [5.7 2.8 4.1 1.3]
 [6.3 2.9 5.6 1.8]
 [6.0 2.7 5.1 1.6]
 [5.6 3.0 4.1 1.3]
 [4.4 2.9 1.4 0.2]
 [5.1 3.8 1.6 0.2]
 [6.7 3.0 5.2 2.3]
 [6.0 2.2 5.0 1.5]
 [6.8 2.8 4.8 1.4]
 [5.1 3.4 1.5 0.2]
 [6.1 2.8 4.7 1.2]
 [6.9 3.1 4.9 1.5]
 [5.0 2.3 3.3 1.0]
 [4.7 3.2 1.6 0.2]
 [5.6 2.7 4.2 1.3]
 [4.4 3.0 1.3 0.2]
 [6.7 3.1 4.7 1.5]
 [4.6 3.6 1.0 0.2]
 [6.1 3.0 4.9 1.8]
 [5.0 3.3 1.4 0.2]
 [4.6 3.2 1.4 0.2]
 [5.0 3.2 1.2 0.2]
 [6.7 2.5 5.8 1.8]
 [7.9 3.8 6.4 2.0]
 [5.3 3.7 1.5 0.2]
 [5.5 4.2 1.4 0.2]
 [7.1 3.0 5.9 2.1]
 [6.4 2.8 5.6 2.2]
 [4.8 3.4 1.9 0.2]
 [7.0 3.2 4.

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.25, random_state = 0)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(112, 4)
(38, 4)
(112, 1)
(38, 1)


In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)
print(X_test.shape)
print(X_train.shape)

(38, 4)
(112, 4)


/home/arkasarkar/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/home/arkasarkar/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/home/arkasarkar/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/home/arkasarkar/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [6]:
import sys
!{sys.executable} -m pip install xgboost

    100% |████████████████████████████████| 127.6MB 427kB/s ta 0:00:01    95% |██████████████████████████████▍ | 121.3MB 4.1MB/s eta 0:00:02


In [7]:
from xgboost import XGBClassifier
model = XGBClassifier()
model.fit(X_train, Y_train)

/home/arkasarkar/anaconda3/lib/python3.7/site-packages/distributed/config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)
/home/arkasarkar/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/arkasarkar/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
       importance_type='gain', interaction_constraints='',
       learning_rate=0.300000012, max_delta_step=0, max_depth=6,
       min_child_weight=1, missing=nan, monotone_constraints='()',
       n_estimators=100, n_jobs=0, num_parallel_tree=1,
       objective='multi:softprob', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=None, subsample=1,
       tree_method='exact', validate_parameters=1, verbosity=None)

In [8]:
y_pred = model.predict(X_test)

In [9]:
print(y_pred)

[1 2 1 0 1 0 0 2 1 0 1 0 0 2 0 1 0 0 2 2 2 1 2 0 2 1 0 1 1 1 2 0 0 0 2 2 2
 2]


In [10]:
Y_test = np.squeeze(Y_test)
print(Y_test)

[1 2 1 0 1 0 0 2 1 0 1 0 0 2 0 1 0 0 2 2 2 1 2 0 2 1 0 1 1 1 2 0 0 0 2 2 2
 2]


In [11]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)

In [12]:
print(cm)

[[14  0  0]
 [ 0 11  0]
 [ 0  0 13]]


In [13]:
cor = 0

for i in range (len(y_pred)):
    if(y_pred[i]==Y_test[i]):
        cor = cor + 1
print("Test set accuracy is : " , cor*100/ len(y_pred) ,"%" )

Test set accuracy is :  100.0 %
